# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('boardID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boardID', to='scrumboard.Board')),
            ],
        ),
    ]
